import: Use nr_cores consistently with the template
ansibleplaybookbundle/import-vm-apb pull request #14
Opened 2018-04-18 07:57 UTC by fabiand

Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

2018-04-18 13:00 UTC, aglitke approved these changes

2018-04-18 13:01 UTC, aglitke requested changes
Updates to apb.yml require you to run apb prepare in the repository to update the Dockerfile with the encoded plan string.

2018-04-18 13:35 UTC, pkliczewski commented
I think that this PR is not needed since we are going to use templates from [here](https://github.com/ansibleplaybookbundle/import-vm-apb/tree/master/templates)

2018-06-12 17:37 UTC, aglitke commented
Closing per Piotr's comment above.

2018-06-12 17:37 UTC, closed without merging