[wip] Libvirt to kubevirt
ansibleplaybookbundle/import-vm-apb pull request #17
Opened 2018-05-03 19:43 UTC by rthallisey

Take a vm from the host's libvirt and pull it into kubevirt

2018-05-03 19:44 UTC, rthallisey commented on bin/libvirt-to-kubevirt.sh
> +  virsh dumpxml $DOMNAME > dom.xml
not sure the best way to talk to the host's libvirt.  ```virsh -c ....```?

2018-05-04 07:20 UTC, pkliczewski requested changes

2018-05-04 07:20 UTC, pkliczewski commented on Dockerfile
> +RUN curl -L -o /usr/bin/kubectl http://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl
We already have oc tool and as far as I can tell we want to use openshift

2018-05-04 07:20 UTC, pkliczewski commented on bin/libvirt-to-kubevirt.sh
> +#!/bin/bash
I wonder whether it would be better to update existing script. We could reuse a lot of code from there.

2018-05-04 07:20 UTC, pkliczewski commented on bin/libvirt-to-kubevirt.sh
> +  xsltproc $PLUGINDIR/data/toVMSpec.xsl dom.xml > vm.yaml
Wouldn't be better to reuse yaml files?

2018-05-04 07:20 UTC, pkliczewski commented on roles/libvirt/tasks/login.yml
> +- name: Login As Super User
We have the same file in import disk and v2v. I think we should share.

2018-05-04 11:19 UTC, rthallisey commented on Dockerfile
> +RUN curl -L -o /usr/bin/kubectl http://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/kubectl
This uses @fabiand 's kubevirt plugin pvc https://github.com/fabiand/kubectl-plugin-pvc.  Not sure what the process is for adding it to oc.

2018-05-04 11:20 UTC, rthallisey commented on bin/libvirt-to-kubevirt.sh
> +#!/bin/bash
:+1:

2022-01-14 16:01 UTC, closed without merging